name: Deploy to Staging

on:
  repository_dispatch:
    types: [deploy-to-staging]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jamesmanning-example-github" #Must be unique in Heroku
          heroku_email: "jamesmanningr98@gmail.com"
          usedocker: true
